package com.example.repartodeaguacdlc.repository

import com.example.repartodeaguacdlc.model.Clientes

class ClientesRepository {
    val clientes = listOf(
        Clientes(1, "Juan Pérez", "juan.perez1@example.com", "https://i.pravatar.cc/300"),
        Clientes(2, "Ana Gómez", "ana.gomez2@example.com", "https://i.pravatar.cc/300"),
        Clientes(3, "Luis Torres", "luis.torres3@example.com", "https://i.pravatar.cc/300"),
        Clientes(4, "María López", "maria.lopez4@example.com", "https://i.pravatar.cc/300"),
        Clientes(5, "Carlos Sánchez", "carlos.sanchez5@example.com", "https://i.pravatar.cc/300"),
        Clientes(6, "Sofía Ramírez", "sofia.ramirez6@example.com", "https://i.pravatar.cc/300"),
        Clientes(7, "José Martínez", "jose.martinez7@example.com", "https://i.pravatar.cc/300"),
        Clientes(8, "Laura Fernández", "laura.fernandez8@example.com", "https://i.pravatar.cc/300"),
        Clientes(9, "Miguel Castro", "miguel.castro9@example.com", "https://i.pravatar.cc/300"),
        Clientes(10, "Valeria Morales", "valeria.morales10@example.com", "https://i.pravatar.cc/300"),
        Clientes(11, "Pedro Vargas", "pedro.vargas11@example.com", "https://i.pravatar.cc/300"),
        Clientes(12, "Camila Reyes", "camila.reyes12@example.com", "https://i.pravatar.cc/300"),
        Clientes(13, "Andrés Domínguez", "andres.dominguez13@example.com", "https://i.pravatar.cc/300"),
        Clientes(14, "Fernanda Ortega", "fernanda.ortega14@example.com", "https://i.pravatar.cc/300"),
        Clientes(15, "Raúl Herrera", "raul.herrera15@example.com", "https://i.pravatar.cc/300"),
        Clientes(16, "Paula Rivas", "paula.rivas16@example.com", "https://i.pravatar.cc/300"),
        Clientes(17, "Diego Navarro", "diego.navarro17@example.com", "https://i.pravatar.cc/300"),
        Clientes(18, "Lucía Paredes", "lucia.paredes18@example.com", "https://i.pravatar.cc/300"),
        Clientes(19, "Javier Ruiz", "javier.ruiz19@example.com", "https://i.pravatar.cc/300"),
        Clientes(20, "Marta Salazar", "marta.salazar20@example.com", "https://i.pravatar.cc/300"),
        Clientes(21, "Tomás Ibáñez", "tomas.ibanez21@example.com", "https://i.pravatar.cc/300"),
        Clientes(22, "Daniela Muñoz", "daniela.munoz22@example.com", "https://i.pravatar.cc/300"),
        Clientes(23, "Ricardo Silva", "ricardo.silva23@example.com", "https://i.pravatar.cc/300"),
        Clientes(24, "Alejandra Soto", "alejandra.soto24@example.com", "https://i.pravatar.cc/300"),
        Clientes(25, "Felipe Campos", "felipe.campos25@example.com", "https://i.pravatar.cc/300"),
        Clientes(26, "Claudia Vega", "claudia.vega26@example.com", "https://i.pravatar.cc/300"),
        Clientes(27, "Héctor Rojas", "hector.rojas27@example.com", "https://i.pravatar.cc/300"),
        Clientes(28, "Natalia Medina", "natalia.medina28@example.com", "https://i.pravatar.cc/300"),
        Clientes(29, "Óscar Delgado", "oscar.delgado29@example.com", "https://i.pravatar.cc/300"),
        Clientes(30, "Carolina Fuentes", "carolina.fuentes30@example.com", "https://i.pravatar.cc/300"),
        Clientes(31, "Iván Gutiérrez", "ivan.gutierrez31@example.com", "https://i.pravatar.cc/300"),
        Clientes(32, "Gabriela Castillo", "gabriela.castillo32@example.com", "https://i.pravatar.cc/300"),
        Clientes(33, "Mauricio Peña", "mauricio.pena33@example.com", "https://i.pravatar.cc/300"),
        Clientes(34, "Adriana Cabrera", "adriana.cabrera34@example.com", "https://i.pravatar.cc/300"),
        Clientes(35, "Hugo Lozano", "hugo.lozano35@example.com", "https://i.pravatar.cc/300"),
        Clientes(36, "Cecilia Bravo", "cecilia.bravo36@example.com", "https://i.pravatar.cc/300"),
        Clientes(37, "Rodrigo León", "rodrigo.leon37@example.com", "https://i.pravatar.cc/300"),
        Clientes(38, "Florencia Álvarez", "florencia.alvarez38@example.com", "https://i.pravatar.cc/300"),
        Clientes(39, "Guillermo Ramos", "guillermo.ramos39@example.com", "https://i.pravatar.cc/300"),
        Clientes(40, "Elena Cortés", "elena.cortes40@example.com", "https://i.pravatar.cc/300"),
        Clientes(41, "Francisco Molina", "francisco.molina41@example.com", "https://i.pravatar.cc/300"),
        Clientes(42, "Patricia Duarte", "patricia.duarte42@example.com", "https://i.pravatar.cc/300"),
        Clientes(43, "Álvaro Núñez", "alvaro.nunez43@example.com", "https://i.pravatar.cc/300"),
        Clientes(44, "Verónica Aguilar", "veronica.aguilar44@example.com", "https://i.pravatar.cc/300"),
        Clientes(45, "Esteban Chávez", "esteban.chavez45@example.com", "https://i.pravatar.cc/300"),
        Clientes(46, "Isabel Herrera", "isabel.herrera46@example.com", "https://i.pravatar.cc/300"),
        Clientes(47, "Mateo Solís", "mateo.solis47@example.com", "https://i.pravatar.cc/300"),
        Clientes(48, "Rocío Carrillo", "rocio.carrillo48@example.com", "https://i.pravatar.cc/300"),
        Clientes(49, "Santiago Cruz", "santiago.cruz49@example.com", "https://i.pravatar.cc/300"),
        Clientes(50, "Daniel Torres", "daniel.torres50@example.com", "https://i.pravatar.cc/300")
    )
}