package com.example.repartodeaguacdlc.repository

import com.example.repartodeaguacdlc.model.Clientes

class ClientesRepository {
    val clientes = listOf(
        Clientes(1, "Juan Pérez", "juan.perez1@example.com", "https://avatar.iran.liara.run/username?username=Juan+Pérez"),
        Clientes(2, "Ana Gómez", "ana.gomez2@example.com", "https://avatar.iran.liara.run/username?username=Ana+Gómez"),
        Clientes(3, "Luis Torres", "luis.torres3@example.com", "https://avatar.iran.liara.run/username?username=Luis+Torres"),
        Clientes(4, "María López", "maria.lopez4@example.com", "https://avatar.iran.liara.run/username?username=María+López"),
        Clientes(5, "Carlos Sánchez", "carlos.sanchez5@example.com", "https://avatar.iran.liara.run/username?username=Carlos+Sánchez"),
        Clientes(6, "Sofía Ramírez", "sofia.ramirez6@example.com", "https://avatar.iran.liara.run/username?username=Sofía+Ramírez"),
        Clientes(7, "José Martínez", "jose.martinez7@example.com", "https://avatar.iran.liara.run/username?username=José+Martínez"),
        Clientes(8, "Laura Fernández", "laura.fernandez8@example.com", "https://avatar.iran.liara.run/username?username=Laura+Fernández"),
        Clientes(9, "Miguel Castro", "miguel.castro9@example.com", "https://avatar.iran.liara.run/username?username=Miguel+Castro"),
        Clientes(10, "Valeria Morales", "valeria.morales10@example.com", "https://avatar.iran.liara.run/username?username=Valeria+Morales"),
        Clientes(11, "Pedro Vargas", "pedro.vargas11@example.com", "https://avatar.iran.liara.run/username?username=Pedro+Vargas"),
        Clientes(12, "Camila Reyes", "camila.reyes12@example.com", "https://avatar.iran.liara.run/username?username=Camila+Reyes"),
        Clientes(13, "Andrés Domínguez", "andres.dominguez13@example.com", "https://avatar.iran.liara.run/username?username=Andrés+Domínguez"),
        Clientes(14, "Fernanda Ortega", "fernanda.ortega14@example.com", "https://avatar.iran.liara.run/username?username=Fernanda+Ortega"),
        Clientes(15, "Raúl Herrera", "raul.herrera15@example.com", "https://avatar.iran.liara.run/username?username=Raúl+Herrera"),
        Clientes(16, "Paula Rivas", "paula.rivas16@example.com", "https://avatar.iran.liara.run/username?username=Paula+Rivas"),
        Clientes(17, "Diego Navarro", "diego.navarro17@example.com", "https://avatar.iran.liara.run/username?username=Diego+Navarro"),
        Clientes(18, "Lucía Paredes", "lucia.paredes18@example.com", "https://avatar.iran.liara.run/username?username=Lucía+Paredes"),
        Clientes(19, "Javier Ruiz", "javier.ruiz19@example.com", "https://avatar.iran.liara.run/username?username=Javier+Ruiz"),
        Clientes(20, "Marta Salazar", "marta.salazar20@example.com", "https://avatar.iran.liara.run/username?username=Marta+Salazar"),
        Clientes(21, "Tomás Ibáñez", "tomas.ibanez21@example.com", "https://avatar.iran.liara.run/username?username=Tomás+Ibáñez"),
        Clientes(22, "Daniela Muñoz", "daniela.munoz22@example.com", "https://avatar.iran.liara.run/username?username=Daniela+Muñoz"),
        Clientes(23, "Ricardo Silva", "ricardo.silva23@example.com", "https://avatar.iran.liara.run/username?username=Ricardo+Silva"),
        Clientes(24, "Alejandra Soto", "alejandra.soto24@example.com", "https://avatar.iran.liara.run/username?username=Alejandra+Soto"),
        Clientes(25, "Felipe Campos", "felipe.campos25@example.com", "https://avatar.iran.liara.run/username?username=Felipe+Campos"),
        Clientes(26, "Claudia Vega", "claudia.vega26@example.com", "https://avatar.iran.liara.run/username?username=Claudia+Vega"),
        Clientes(27, "Héctor Rojas", "hector.rojas27@example.com", "https://avatar.iran.liara.run/username?username=Héctor+Rojas"),
        Clientes(28, "Natalia Medina", "natalia.medina28@example.com", "https://avatar.iran.liara.run/username?username=Natalia+Medina"),
        Clientes(29, "Óscar Delgado", "oscar.delgado29@example.com", "https://avatar.iran.liara.run/username?username=Óscar+Delgado"),
        Clientes(30, "Carolina Fuentes", "carolina.fuentes30@example.com", "https://avatar.iran.liara.run/username?username=Carolina+Fuentes"),
        Clientes(31, "Iván Gutiérrez", "ivan.gutierrez31@example.com", "https://avatar.iran.liara.run/username?username=Iván+Gutiérrez"),
        Clientes(32, "Gabriela Castillo", "gabriela.castillo32@example.com", "https://avatar.iran.liara.run/username?username=Gabriela+Castillo"),
        Clientes(33, "Mauricio Peña", "mauricio.pena33@example.com", "https://avatar.iran.liara.run/username?username=Mauricio+Peña"),
        Clientes(34, "Adriana Cabrera", "adriana.cabrera34@example.com", "https://avatar.iran.liara.run/username?username=Adriana+Cabrera"),
        Clientes(35, "Hugo Lozano", "hugo.lozano35@example.com", "https://avatar.iran.liara.run/username?username=Hugo+Lozano"),
        Clientes(36, "Cecilia Bravo", "cecilia.bravo36@example.com", "https://avatar.iran.liara.run/username?username=Cecilia+Bravo"),
        Clientes(37, "Rodrigo León", "rodrigo.leon37@example.com", "https://avatar.iran.liara.run/username?username=Rodrigo+León"),
        Clientes(38, "Florencia Álvarez", "florencia.alvarez38@example.com", "https://avatar.iran.liara.run/username?username=Florencia+Álvarez"),
        Clientes(39, "Guillermo Ramos", "guillermo.ramos39@example.com", "https://avatar.iran.liara.run/username?username=Guillermo+Ramos"),
        Clientes(40, "Elena Cortés", "elena.cortes40@example.com", "https://avatar.iran.liara.run/username?username=Elena+Cortés"),
        Clientes(41, "Francisco Molina", "francisco.molina41@example.com", "https://avatar.iran.liara.run/username?username=Francisco+Molina"),
        Clientes(42, "Patricia Duarte", "patricia.duarte42@example.com", "https://avatar.iran.liara.run/username?username=Patricia+Duarte"),
        Clientes(43, "Álvaro Núñez", "alvaro.nunez43@example.com", "https://avatar.iran.liara.run/username?username=Álvaro+Núñez"),
        Clientes(44, "Verónica Aguilar", "veronica.aguilar44@example.com", "https://avatar.iran.liara.run/username?username=Verónica+Aguilar"),
        Clientes(45, "Esteban Chávez", "esteban.chavez45@example.com", "https://avatar.iran.liara.run/username?username=Esteban+Chávez"),
        Clientes(46, "Isabel Herrera", "isabel.herrera46@example.com", "https://avatar.iran.liara.run/username?username=Isabel+Herrera"),
        Clientes(47, "Mateo Solís", "mateo.solis47@example.com", "https://avatar.iran.liara.run/username?username=Mateo+Solís"),
        Clientes(48, "Rocío Carrillo", "rocio.carrillo48@example.com", "https://avatar.iran.liara.run/username?username=Rocío+Carrillo"),
        Clientes(49, "Santiago Cruz", "santiago.cruz49@example.com", "https://avatar.iran.liara.run/username?username=Santiago+Cruz"),
        Clientes(50, "Daniel Torres", "daniel.torres50@example.com", "https://avatar.iran.liara.run/username?username=Daniel+Torres")
    )
}